---
:ems:
  :ems_nuage:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:http_proxy:
  :nuage:
    :host:
    :password:
    :port:
    :user:
:ems_refresh:
  :nuage_network:
    :inventory_object_refresh: true
    :allow_targeted_refresh: true
:product:
  :nuage: true
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_nuage_network:
        :topics:
          - topic/CNAMessages
